# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myproto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmyproto.proto\"/\n\x03\x44og\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\r\n\x05\x63olor\x18\x03 \x01(\t\",\n\x08\x44ogGroup\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\x04\x64ogs\x18\x02 \x03(\x0b\x32\x04.Dogb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myproto_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DOG']._serialized_start=17
  _globals['_DOG']._serialized_end=64
  _globals['_DOGGROUP']._serialized_start=66
  _globals['_DOGGROUP']._serialized_end=110
# @@protoc_insertion_point(module_scope)
